In [1]:
import pandas as pd
import numpy as np


import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import pandas as pd
df=pd.read_csv(r'F:\dm\1 - Copy\master.csv')
print (df)

      Year Area affected Population affected Damage to Crops(area)  \
0     1953           Nil                 Nil                   Nil
1     1954           Nil                 Nil                   Nil
2     1955           Nil                 Nil                   Nil
3     1956           Nil                 Nil                   Nil
4     1957           Nil                 Nil                   Nil
...    ...           ...                 ...                   ...
2235  2012             0               0.529                 0.012
2236  2013         0.182               3.112                 0.182
2237  2014         0.051               0.448                 0.051
2238  2015           1.3               10.84                   1.3
2239  2016           NaN                 NaN                   NaN

     Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                       Nil                      Nil                     Nil
1                       Nil                      Nil                     Nil
2                       Nil                      Nil                     Nil
3                       Nil                      Nil                     Nil
4                       Nil                      Nil                     Nil
...                     ...                      ...                     ...
2235                 20.617                    49132                  33.017
2236                 533.95                   233336                  178.97
2237                  6.132                    33621                  17.275
2238               11433.68                   830245                 7895.63
2239                    NaN                      NaN                     NaN

     Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                    Nil                      Nil                        Nil
1                    Nil                      Nil                        Nil
2                    Nil                      Nil                        Nil
3                    Nil                      Nil                        Nil
4                    Nil                      Nil                        Nil
...                  ...                      ...                        ...
2235                2200                       29                    632.949
2236               28311                       41                      13.58
2237                 145                      169                      2.668
2238               22774                      338                    6023.96
2239                 NaN                      NaN                        NaN

     Damage to crops,houses,public utilities            Place
0                                        Nil  Andaman Nicobar
1                                        Nil  Andaman Nicobar
2                                        Nil  Andaman Nicobar
3                                        Nil  Andaman Nicobar
4                                        Nil  Andaman Nicobar
...                                      ...              ...
2235                                 686.583      West Bengal
2236                                   726.5      West Bengal
2237                                  26.075      West Bengal
2238                                25353.27      West Bengal
2239                                       0      West Bengal

[2240 rows x 12 columns]

In [4]:
df.describe(include='all')

,Year,Area affected,Population affected,Damage to Crops(area),Damage to Crops(value),Damage to Houses(number),Damage to Houses(value),Cattle lost(number),Human lives lost(number),Damage to public utilities,"Damage to crops,houses,public utilities",Place
count,2240.000000,2199,2208,2207,2198,2214,2196,2207,2215,2204,2237,2240
unique,NaN,359,548,306,797,989,650,640,271,717,952,35
top,NaN,Nil,Nil,Nil,Nil,Nil,Nil,Nil,Nil,Nil,Nil,Andhra Pradesh
freq,NaN,635,699,659,645,665,664,776,776,726,581,64
mean,1984.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,18.477078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1953.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1968.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1984.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2000.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2016.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.isnull().sum()

Year                                        0
Area affected                              41
Population affected                        32
Damage to Crops(area)                      33
Damage to Crops(value)                     42
Damage to Houses(number)                   26
Damage to Houses(value)                    44
Cattle lost(number)                        33
Human lives lost(number)                   25
Damage to public utilities                 36
Damage to crops,houses,public utilities     3
Place                                       0
dtype: int64

In [6]:
df.dtypes

Year                                        int64
Area affected                              object
Population affected                        object
Damage to Crops(area)                      object
Damage to Crops(value)                     object
Damage to Houses(number)                   object
Damage to Houses(value)                    object
Cattle lost(number)                        object
Human lives lost(number)                   object
Damage to public utilities                 object
Damage to crops,houses,public utilities    object
Place                                      object
dtype: object

In [7]:
temp = pd.DataFrame(index=df.columns)
temp['data_type'] = df.dtypes
temp['null_count'] = df.isnull().sum()
temp['unique_count'] = df.nunique()

In [8]:
temp

                                        data_type  null_count  unique_count
Year                                        int64           0            64
Area affected                              object          41           359
Population affected                        object          32           548
Damage to Crops(area)                      object          33           306
Damage to Crops(value)                     object          42           797
Damage to Houses(number)                   object          26           989
Damage to Houses(value)                    object          44           650
Cattle lost(number)                        object          33           640
Human lives lost(number)                   object          25           271
Damage to public utilities                 object          36           717
Damage to crops,houses,public utilities    object           3           952
Place                                      object           0            35

In [15]:
import pandas as pd
df1=pd.read_csv(r'F:\dm\1 - Copy\Andaman Nicobar.csv')
print (df1)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL          0.03               0.042                  0.03
65      NaN  Average         0.001               0.002                 0.001
66      NaN  Maximum          0.03                0.04                  0.03
67      NaN   (Year)          1988                1988                  1988

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                    NaN                      NaN                     NaN
64                  0.799                      390                   0.402
65                   0.03                       14                   0.015
66                  0.477                      192                    0.38
67                   1988                     1988                    1988

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 NaN                      NaN                        NaN
64                  46                     1473                      0.086
65                   2                       55                      0.003
66                  20                     1465                       0.07
67                1985                     1988                       1985

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                      Nil
4                                      Nil
..                                     ...
63                                       0
64                                   1.287
65                                   0.044
66                                    0.69
67                                    1988

[68 rows x 12 columns]

In [16]:
import pandas as pd
df2=pd.read_csv(r'F:\dm\1 - Copy\Andhra Pradesh.csv')
print (df2)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953          0.07                2.66                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Neg                 Nil                  0.19
3       4.0     1956          1.39                 0.2                  0.05
4       5.0     1957          0.01                 Nil                  0.01
..      ...      ...           ...                 ...                   ...
63     64.0     2016         0.003               0.386                 0.003
64      NaN    Total        23.249             122.917                17.129
65      NaN  Average         0.517               2.998                 0.343
66      NaN  Maximum          9.04               13.42                 1.995
67      NaN   (Year)         -2005               -1969                 -2010

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                    1.26                     3561                    0.07
3                    0.27                     3460                    0.02
4                       0                    17560                   0.121
..                    ...                      ...                     ...
63                    NaN                      NaN                     NaN
64              13977.651                  6716437                4592.756
65                285.258                   129162                  99.843
66                3758.87                  1063879                  904.75
67                  -2010                    -1977                   -2007

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                40509                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                 1358                       18                       0.11
3                    4                      126                       0.04
4                 4630                       66                        0.4
..                 ...                      ...                        ...
63                   4                        3                        NaN
64             1499191                    16835                  41166.459
65               30596                      324                    807.185
66              500978                     9974                   10678.67
67               -1977                    -1977                      -2009

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                     1.44
3                                     0.33
4                                    0.521
..                                     ...
63                                       0
64                               59736.866
65                                1127.111
66                                12616.13
67                                   -2010

[68 rows x 12 columns]

In [17]:
import pandas as pd
df3=pd.read_csv(r'F:\dm\1 - Copy\Arunachal Pradesh.csv')
print (df3)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL         1.447               14.11                  0.66
65      NaN  Average         0.063               0.487                  0.03
66      NaN  Maximum          0.31                 4.5                  0.31
67      NaN   (Year)          2013                2010                 -2013

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                    NaN                      354                     NaN
64               6261.071                   102839                 370.895
65                 240.81                     4285                  16.859
66                   5678                    40504                  259.36
67                   2003                     2008                    2010

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63               15671                       42                        NaN
64              101726                      702                  10787.088
65                4423                       28                    326.881
66               25472                      127                   2335.408
67                2008                     2003                       2014

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                      Nil
4                                      Nil
..                                     ...
63                                       0
64                               17419.053
65                                 470.785
66                                6024.659
67                                    2003

[68 rows x 12 columns]

In [18]:
import pandas as pd
df4=pd.read_csv(r'F:\dm\1 - Copy\Assam.csv')
print (df4)

    Sl. No.     Year  Area affected  Population affected  \
0       1.0     1953          0.080                0.410
1       2.0     1954          3.150                1.680
2       3.0     1955          1.410                0.800
3       4.0     1956          0.600                0.560
4       5.0     1957          0.400                0.310
..      ...      ...            ...                  ...
63     64.0     2016          0.000                0.003
64      NaN    TOTAL         51.564              166.313
65      NaN  Average          0.806                2.599
66      NaN  Maximum          3.820               12.637
67      NaN   (Year)      -1988.000            -2004.000

   Damage to Crops(area)  Damage to Crops(value) Damage to Houses(number)  \
0                    Neg                   2.120                      Neg
1                   0.27                  10.620                      Nil
2                   0.09                   2.466                      Nil
3                   0.08                   3.098                     8737
4                   0.02                   1.007                     1867
..                   ...                     ...                      ...
63                     0                     NaN                      NaN
64                25.351                2406.831                  4335003
65                 0.402                  38.820                    72250
66                  9.84                 463.304                   663168
67                 -2005               -1998.000                     2004

   Damage to Houses(value)  Cattle lost(number)  Human lives lost(number)  \
0                     0.29                837.0                       4.0
1                      Nil              16505.0                      32.0
2                      Nil               3558.0                       0.0
3                     0.13               1561.0                      19.0
4                    0.043                267.0                       5.0
..                     ...                  ...                       ...
63                     NaN                  NaN                      36.0
64                 439.312             679578.0                    2933.0
65                   7.322              10961.0                      47.0
66                  103.92             118772.0                     497.0
67                   -1988               2004.0                   -2004.0

   Damage to public utilities  Damage to crops,houses,public utilities
0                        0.25                                    2.660
1                       5.147                                   15.767
2                        1.24                                    3.706
3                       0.036                                    3.264
4                       3.465                                    4.515
..                        ...                                      ...
63                      17.89                                   17.890
64                   5051.083                                 7897.226
65                     82.805                                  123.394
66                    3200.31                                 3200.310
67                      -2012                                -2012.000

[68 rows x 12 columns]

In [19]:
import pandas as pd
df5=pd.read_csv(r'F:\dm\1 - Copy\Bihar.csv')
print (df5)

    Sl. No.     Year  Area affected  Population affected  \
0       1.0     1953          0.970                6.770
1       2.0     1954          2.500                7.670
2       3.0     1955          1.770                7.110
3       4.0     1956          1.320                3.120
4       5.0     1957          0.790                1.730
..      ...      ...            ...                  ...
63     64.0     2016          0.410                8.823
64      NaN    TOTAL         81.694              404.077
65      NaN  Average          1.297                6.314
66      NaN  Maximum          4.260               29.985
67      NaN   (Year)      -1971.000             2004.000

   Damage to Crops(area) Damage to Crops(value)  Damage to Houses(number)  \
0                   0.93                     29                    184300
1                   1.59                     15                    179451
2                   1.01                   20.3                    111356
3                    0.4                   5.22                     79879
4                    0.3                    Neg                     18812
..                   ...                    ...                       ...
63                  0.41                 443.53                     16717
64                36.693               6266.684                   9864595
65                 0.582                106.215                    154134
66                  2.24                768.378                   1398484
67                 -1987                  -2007                     -1987

   Damage to Houses(value) Cattle lost(number) Human lives lost(number)  \
0                        6                  33                        5
1                        5                1944                       63
2                     1.12                  57                       44
3                     0.51                 138                       32
4                      Neg                  18                        7
..                     ...                 ...                      ...
63                  44.262                 246                      254
64                3330.375               56351                    10574
65                  59.471                 909                      173
66                 831.445               10105                     1287
67                   -2007               -1961                    -2007

   Damage to public utilities Damage to crops,houses,public utilities
0                         1.5                                    36.5
1                         1.5                                    21.5
2                       0.205                                  21.625
3                         Nil                                    5.73
4                         Nil                                     Neg
..                        ...                                     ...
63                      40.97                                 528.762
64                   5033.111                               14630.171
65                       88.3                                  235.97
66                    1035.16                                2310.647
67                      -2003                                   -2004

[68 rows x 12 columns]

In [20]:
import pandas as pd
df6=pd.read_csv(r'F:\dm\1 - Copy\Chandigarh.csv')
print (df6)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016           Nil                 Nil                   Nil
64      NaN    TOTAL             0                   0                     0
65      NaN  Average             0                   0                     0
66      NaN  Maximum             0                   0                     0
67      NaN   (Year)         -2004               -2004                 -2004

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                    Nil                      Nil                     Nil
64                      0                        0                       0
65                      0                        0                       0
66                      0                        0                       0
67                  -2004                    -2004                   -2004

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 Nil                      Nil                        Nil
64                   0                        0                      0.418
65                   0                        0                      0.025
66                   0                        0                      0.418
67               -2004                    -2004                      -2004

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                      Nil
4                                      Nil
..                                     ...
63                                     Nil
64                                   0.418
65                                   0.025
66                                   0.418
67                                   -2004

[68 rows x 12 columns]

In [21]:
import pandas as pd
df7=pd.read_csv(r'F:\dm\1 - Copy\Chattisgarh.csv')
print (df7)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953          0.26                0.05                   Neg
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955          0.03                 Neg                   Nil
3       4.0     1956          0.04                0.02                   Nil
4       5.0     1957          0.03                 Nil                  0.02
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL         0.161               2.249                 0.149
65      NaN  Average         0.013               0.187                 0.012
66      NaN  Maximum         0.089               0.676                 0.089
67      NaN   (Year)         -2001               -2003                 -2001

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                    0.07                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                       3                     1196                       4
3                     Nil                      310                     1.1
4                     Neg                      426                   0.012
..                    ...                      ...                     ...
63                    NaN                      NaN                     NaN
64                118.594                   186384                 113.818
65                  9.883                    15532                   9.485
66                  50.74                    43635                  27.718
67                  -2001                    -2006                   -2006

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                 2872                        2                       0.05
1                  Nil                       10                          1
2                  266                        5                       0.01
3                   43                      Nil                      1.015
4                   71                      Nil                       0.08
..                 ...                      ...                        ...
63                 NaN                      NaN                        NaN
64               12606                     1090                    366.489
65                1051                       91                     30.541
66                9216                      252                     167.95
67               -2006                    -2006                      -2001

   Damage to crops,houses,public utilities
0                                     0.12
1                                        1
2                                     7.01
3                                    2.115
4                                    0.092
..                                     ...
63                                       0
64                                 598.901
65                                  37.431
66                                  231.37
67                                   -2001

[68 rows x 12 columns]

In [22]:
import pandas as pd
df8=pd.read_csv(r'F:\dm\1 - Copy\Dadra & Nagar Haveli.csv')
print (df8)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016           Nil                 Nil                   Nil
64      NaN    TOTAL             3                   4                     5
65      NaN  Average             0                   0                     0
66      NaN  Maximum             0                   0                     0
67      NaN   (Year)         -1976              (----)                 -1976

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                    Nil                      Nil                     Nil
64                   6.02                      141                       8
65                  0.001                        8                       0
66                   0.02                      134                       0
67                  -1976                    -1976                   -1976

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 Nil                      Nil                        Nil
64                  46                       14                     11.149
65                   2                        0                      0.009
66                  37                        4                      0.149
67               -1976                    -1976                      -1976

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                      Nil
4                                      Nil
..                                     ...
63                                     Nil
64                                  12.169
65                                   0.011
66                                   0.169
67                                    1976

[68 rows x 12 columns]

In [23]:
import pandas as pd
df9=pd.read_csv(r'F:\dm\1 - Copy\Daman & Diu.csv')
print (df9)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016             0                   0                     0
64      NaN    TOTAL             0                0.01                     0
65      NaN  Average             0               0.001                     0
66      NaN  Maximum             0                0.01                     0
67      NaN   (Year)         -2005               -2004                 -2005

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                      0                        0                       0
64                      0                    10000                    0.26
65                      0                      526                   0.014
66                      0                    10000                    0.26
67                  -2005                    -2004                   -2004

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                   0                        0                          0
64                   0                       28                      3.115
65                   0                        2                      0.164
66                   0                       28                      3.115
67               -2005                    -2003                      -2004

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                      Nil
4                                      Nil
..                                     ...
63                                       0
64                                   3.375
65                                   0.178
66                                   3.375
67                                   -2004

[68 rows x 12 columns]

In [24]:
import pandas as pd
df10=pd.read_csv(r'F:\dm\1 - Copy\Delhi.csv')
print (df10)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955          0.03                 Nil                   Neg
3       4.0     1956          0.01                 0.1                  0.01
4       5.0     1957          0.01                 Neg                   Neg
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL         0.923               3.716                 0.312
65      NaN  Average         0.023               0.098                 0.009
66      NaN  Maximum         0.458               1.854                 0.155
67      NaN   (Year)         -1997               -1997                 -1997

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                    0.15                      Neg                    0.14
3                    0.04                     1700                    0.02
4                   0.021                      Nil                     Nil
..                    ...                      ...                     ...
63                    NaN                      NaN                     NaN
64                 51.168                   133478                  19.394
65                  1.163                     3608                   0.554
66                 25.579                    66739                   9.697
67                  -1997                    -1997                   -1997

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                   24                        7                       0.03
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 NaN                      NaN                        NaN
64                1320                      104                     61.066
65                  46                        3                      2.181
66                 660                       52                     30.533
67               -1997                    -1997                      -1997

   Damage to crops,houses,public utilities
0                                        0
1                                        0
2                                     0.32
3                                     0.06
4                                    0.021
..                                     ...
63                                       0
64                                 131.628
65                                   2.581
66                                  65.809
67                                   -1997

[68 rows x 12 columns]

In [25]:
import pandas as pd
df11=pd.read_csv(r'F:\dm\1 - Copy\Goa.csv')
print (df11)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016             0                   0                     0
64      NaN    TOTAL             0               0.055                 0.007
65      NaN  Average             0               0.002                     0
66      NaN  Maximum             0               0.053                 0.004
67      NaN   (Year)          1974                1976                  2001

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                      0                        0                       0
64                  1.639                     2401                   4.947
65                  0.055                       80                   0.177
66                  0.623                      682                   1.464
67                   2011                     2000                    2009

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                   0                        0                          0
64                  37                       19                      1.081
65                   1                        1                       0.04
66                  20                       10                          1
67                2000                     2008                       2000

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                      Nil
4                                      Nil
..                                     ...
63                                       0
64                                    7.47
65                                   0.267
66                                   1.955
67                                    2000

[68 rows x 12 columns]

In [26]:
import pandas as pd
df12=pd.read_csv(r'F:\dm\1 - Copy\Gujarat.csv')
print (df12)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Neg
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956          0.26                0.01                   Neg
4       5.0     1957          0.08                0.01                   Neg
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN               0.012                   NaN
64      NaN    TOTAL         15.62             101.322                11.424
65      NaN  Average         0.355               1.809                 0.266
66      NaN  Maximum          2.05              16.486                  1.49
67      NaN   (Year)         -1988               -1996                 -1988

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                   0.013                      Neg                   0.031
2                     Nil                      Nil                     Nil
3                   0.287                      Neg                   0.184
4                    0.68                      Neg                    0.09
..                    ...                      ...                     ...
63                    NaN                      128                     NaN
64               1426.572                  2220394                3038.968
65                 26.418                    43537                  64.659
66                 772.26                   387400                 2458.85
67                   2010                    -1982                    2006

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                 6500                       11                      0.215
4                  618                        8                      0.123
..                 ...                      ...                        ...
63                 322                       99                        NaN
64              721333                     9205                   1161.884
65               13610                      170                     21.516
66              200555                     2005                     134.74
67               -1982                    -1979                      -1988

   Damage to crops,houses,public utilities
0                                      Nil
1                                    0.044
2                                      Nil
3                                    0.686
4                                    0.893
..                                     ...
63                                       0
64                                5627.424
65                                  92.253
66                                 2458.85
67                                    2006

[68 rows x 12 columns]

In [27]:
import pandas as pd
df13=pd.read_csv(r'F:\dm\1 - Copy\Haryana.csv')
print (df13)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Neg                 Nil                   Nil
1       2.0     1954           Neg                0.02                   Neg
2       3.0     1955          0.13                1.26                  0.12
3       4.0     1956          0.03                 Nil                  0.02
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016         0.004                   0                 0.004
64      NaN    TOTAL         9.285              24.999                 6.151
65      NaN  Average         0.193               0.521                 0.134
66      NaN  Maximum             1                3.04                   0.8
67      NaN   (Year)         -1977               -1977                 -1977

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Neg                      Nil                     Nil
2                     2.8                    25121                    0.42
3                   3.319                     2159                    0.02
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                518.235                       49                   4.212
64                2186.16                  1480245                 146.135
65                 42.866                    29024                   3.044
66                518.235                   534766                   50.71
67                  -2016                    -1993                   -1988

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  292                        2                       0.02
3                  Nil                      Nil                        Neg
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                   1                        2                          0
64                7850                      588                    186.315
65                 178                       14                      4.436
66                2637                       50                      63.82
67               -1978                    -1977                      -1988

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Neg
2                                     3.24
3                                    3.339
4                                      Nil
..                                     ...
63                                 522.447
64                                 2518.09
65                                   51.39
66                                 522.447
67                                   -2016

[68 rows x 12 columns]

In [28]:
import pandas as pd
df14=pd.read_csv(r'F:\dm\1 - Copy\Himachal Pradesh.csv')
print (df14)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956          Neg.                 Nil                  Neg.
4       5.0     1957          0.23                0.09                  0.01
..      ...      ...           ...                 ...                   ...
63     64.0     2016         0.035               6.865                 0.035
64      NaN    TOTAL         9.307              49.258                 4.502
65      NaN  Average         0.332               1.493                  0.15
66      NaN  Maximum          2.87               6.865                 0.476
67      NaN   (Year)         -1999               -2015                 -1994

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                    0.01                      Nil                     Nil
4                   0.078                      447                   0.034
..                    ...                      ...                     ...
63                  26.83                     2283                   15.27
64               4635.576                   235959                1065.419
65                110.371                     4815                  25.367
66                    506                    25183                     200
67                  -2013                    -1995                   -2013

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                       13                       0.01
4                  204                       21                       0.01
..                 ...                      ...                        ...
63                 136                       40                       3.02
64               82669                     2716                  10685.452
65                1722                       53                    248.499
66               24267                      279                    2228.37
67               -2013                    -1978                      -2013

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                     0.02
4                                    0.122
..                                     ...
63                                   45.12
64                               16386.447
65                                 348.648
66                                 2934.37
67                                   -2013

[68 rows x 12 columns]

In [29]:
import pandas as pd
df15=pd.read_csv(r'F:\dm\1 - Copy\Jammu & Kashmir.csv')
print (df15)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954          0.05                 0.1                   Neg
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957          0.05                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL         1.973               8.532                  1.79
65      NaN  Average         0.056               0.267                 0.058
66      NaN  Maximum         0.651               2.078                 0.651
67      NaN   (Year)          2014                1992                  2014

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                    0.27                      Neg                     0.3
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                    NaN                      NaN                     NaN
64               5921.058                   434582                 204.166
65                169.173                    12072                   5.833
66                   5611                   104206                   135.4
67                   2014                     2014                    1992

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                 1000                       15                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                       14                      0.198
..                 ...                      ...                        ...
63                 NaN                        3                        NaN
64              244926                     1733                   3509.721
65                6445                       41                     85.603
66               53833                      354                       3000
67                1992                     1992                       2014

   Damage to crops,houses,public utilities
0                                      Nil
1                                     0.57
2                                      Nil
3                                      Nil
4                                    0.198
..                                     ...
63                                       0
64                                9634.945
65                                  214.11
66                                    8611
67                                    2014

[68 rows x 12 columns]

In [30]:
import pandas as pd
df16=pd.read_csv(r'F:\dm\1 - Copy\Jharkhand.csv')
print (df16)

    Sl. No.     Year  Area affected  Population affected  \
0       1.0     1953          0.970                6.770
1       2.0     1954          2.500                7.670
2       3.0     1955          1.770                7.110
3       4.0     1956          1.320                3.120
4       5.0     1957          0.790                1.730
..      ...      ...            ...                  ...
63     64.0     2016            NaN                  NaN
64      NaN    TOTAL          0.063                0.366
65      NaN  Average          0.005                0.026
66      NaN  Maximum          0.041                0.199
67      NaN   (Year)      -2012.000            -2013.000

   Damage to Crops(area) Damage to Crops(value)  Damage to Houses(number)  \
0                   0.93                     29                  184300.0
1                   1.59                     15                  179451.0
2                   1.01                   20.3                  111356.0
3                    0.4                   5.22                   79879.0
4                    0.3                    Neg                   18812.0
..                   ...                    ...                       ...
63                   NaN                    NaN                       NaN
64                 0.063                  6.946                    4980.0
65                 0.005                  0.496                     356.0
66                 0.041                  3.894                    3041.0
67                 -2012                  -2013                   -2012.0

   Damage to Houses(value) Cattle lost(number) Human lives lost(number)  \
0                        6                  33                        5
1                        5                1944                       63
2                     1.12                  57                       44
3                     0.51                 138                       32
4                      Neg                  18                        7
..                     ...                 ...                      ...
63                     NaN                 NaN                      NaN
64                   2.179                   2                       13
65                   0.156                   0                        1
66                   1.144                   1                        9
67                   -2008               -2008                    -2012

   Damage to public utilities Damage to crops,houses,public utilities
0                         1.5                                    36.5
1                         1.5                                    21.5
2                       0.205                                  21.625
3                         Nil                                    5.73
4                         Nil                                     Neg
..                        ...                                     ...
63                        NaN                                       0
64                          0                                   9.125
65                          0                                    0.57
66                          0                                   4.096
67                    (-----)                                   -2013

[68 rows x 12 columns]

In [31]:
import pandas as pd
df17=pd.read_csv(r'F:\dm\1 - Copy\Karnataka.csv')
print (df17)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Neg                 Neg                   Neg
..      ...      ...           ...                 ...                   ...
63     64.0     2016          3.78                2.18                  3.78
64      NaN    TOTAL        11.323               34.06                10.822
65      NaN  Average         0.276               0.873                 0.277
66      NaN  Maximum          3.78                  18                  3.78
67      NaN   (Year)         -2016               -2009                 -2016

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                   0.017                      294                     Neg
..                    ...                      ...                     ...
63                1771.26                    21224                    5.37
64              12196.608                  1685925               10804.432
65                 234.55                    31221                 225.092
66                3028.57                   666361                 9892.12
67                  -2009                    -2009                   -2009

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 521                       63                     236.18
64               61430                     3127                  14209.348
65                1335                       68                    273.257
66               13264                      396                     5052.5
67               -2007                    -2009                      -2009

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                      Nil
4                                    0.017
..                                     ...
63                                 2012.81
64                               37210.388
65                                 676.553
66                                17973.19
67                                   -2009

[68 rows x 12 columns]

In [32]:
import pandas as pd
df18=pd.read_csv(r'F:\dm\1 - Copy\Kerala.csv')
print (df18)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956          0.02                0.03                   Neg
4       5.0     1957          0.29                0.33                  0.01
..      ...      ...           ...                 ...                   ...
63     64.0     2016         0.002               0.006                 0.002
64      NaN    TOTAL         8.039              84.604                 2.888
65      NaN  Average         0.161               1.627                 0.059
66      NaN  Maximum          1.47                14.6                 0.578
67      NaN   (Year)          1989                1985                  1991

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Neg                     2727                    0.03
4                   0.113                     7473                   0.024
..                    ...                      ...                     ...
63                  42.68                     5809                     NaN
64               2473.918                  1929041                 586.967
65                 46.678                    35073                  11.509
66                 413.15                   478514                  117.64
67                   1992                     1985                    1986

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                        5                        Nil
4                   12                        4                        Nil
..                 ...                      ...                        ...
63                  56                       66                        NaN
64              132856                     3857                   5062.873
65                2827                       70                    101.257
66               80059                      265                   1015.319
67                2013                     1992                       1997

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                     0.03
4                                    0.137
..                                     ...
63                                   42.68
64                                8123.758
65                                 147.705
66                                 1325.36
67                                    1992

[68 rows x 12 columns]

In [33]:
import pandas as pd
df19=pd.read_csv(r'F:\dm\1 - Copy\Lakshadweep.csv')
print (df19)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL             0               0.032                     0
65      NaN  Average             0               0.002                     0
66      NaN  Maximum             0               0.032                     0
67      NaN   (Year)         -1978                1978                 -1978

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                    NaN                      NaN                     NaN
64                  0.088                      275                   0.015
65                  0.005                       15                   0.001
66                  0.088                      275                   0.015
67                  -1978                    -1978                   -1978

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 NaN                      NaN                        NaN
64                   0                        0                      0.006
65                   0                        0                          0
66                   0                        0                      0.006
67               -1978                    -1978                      -1978

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                      Nil
4                                      Nil
..                                     ...
63                                     NaN
64                                   0.109
65                                   0.006
66                                   0.109
67                                   -1978

[68 rows x 12 columns]

In [35]:
import pandas as pd
df20=pd.read_csv(r'F:\dm\1 - Copy\Madhya Pradesh.csv')
print (df20)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953          0.26                0.05                   Neg
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955          0.03                 Neg                   Nil
3       4.0     1956          0.04                0.02                   Nil
4       5.0     1957          0.03                 Nil                  0.02
..      ...      ...           ...                 ...                   ...
63     64.0     2016         1.304                1.56                 1.304
64      NaN    TOTAL         8.055              42.736                 7.243
65      NaN  Average         0.192               0.971                 0.191
66      NaN  Maximum          3.67               14.72                  3.67
67      NaN   (Year)          2013               -2014                 -2013

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                    0.07                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                       3                     1196                       4
3                     Nil                      310                     1.1
4                     Neg                      426                   0.012
..                    ...                      ...                     ...
63                    NaN                   168267                     NaN
64                204.437                  1300241                 229.039
65                  4.986                    24079                   4.979
66                 58.828                   244700                  173.88
67                  -1973                    -1994                   -2005

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                 2872                        2                       0.05
1                  Nil                       10                          1
2                  266                        5                       0.01
3                   43                      Nil                      1.015
4                   71                      Nil                       0.08
..                 ...                      ...                        ...
63                2623                      327                     207.86
64              169461                     2564                   1107.908
65                3197                       51                     23.573
66               71037                      390                     464.06
67               -1973                    -2014                      -2014

   Damage to crops,houses,public utilities
0                                     0.12
1                                        1
2                                     7.01
3                                    2.115
4                                    0.092
..                                     ...
63                                  207.86
64                                1541.384
65                                  28.544
66                                  464.06
67                                   -2014

[68 rows x 12 columns]

In [36]:
import pandas as pd
df21=pd.read_csv(r'F:\dm\1 - Copy\Maharashtra.csv')
print (df21)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Neg                0.02                   Neg
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016         0.015               0.077                 0.015
64      NaN    TOTAL         2.444              14.994                 2.254
65      NaN  Average         0.054                 0.3                  0.05
66      NaN  Maximum         0.391                4.17                 0.391
67      NaN   (Year)         -2002               -1984                 -2002

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                   0.208                     6757                   0.053
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                    NaN                     8164                     NaN
64                304.717                  1255328                 216.315
65                   5.86                    22417                   4.326
66                 74.488                   285540                  52.727
67                  -2003                    -1983                   -1994

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                        8                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                1036                      145                        NaN
64               91724                     4598                    331.354
65                1699                       87                       7.05
66               20927                      917                     114.29
67               -1983                    -1989                      -1994

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                    0.261
4                                      Nil
..                                     ...
63                                       0
64                                 852.386
65                                  14.954
66                                 228.597
67                                   -1994

[68 rows x 12 columns]

In [37]:
import pandas as pd
df22=pd.read_csv(r'F:\dm\1 - Copy\Manipur.csv')
print (df22)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953             0                0.02                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Neg                 Nil                   Nil
4       5.0     1957           Neg                 Neg                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL         2.349               3.891                 1.268
65      NaN  Average         0.053                0.09                 0.033
66      NaN  Maximum         0.116                0.73                  0.08
67      NaN   (Year)         -2002               -1989                 -1989

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      292                    0.02
4                     Nil                        3                     Neg
..                    ...                      ...                     ...
63                    NaN                      NaN                     NaN
64                286.438                   132989                 114.642
65                  6.986                     2891                   3.185
66                  35.05                    52884                      43
67                  -2015                    -1989                   -2015

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                 1436                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                    1                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 NaN                      NaN                        NaN
64                6525                       48                    524.436
65                 384                        4                     13.111
66                3210                       16                     396.64
67               -1986                    -2015                      -2015

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                     0.02
4                                      Neg
..                                     ...
63                                       0
64                                 925.516
65                                   20.12
66                                  474.69
67                                   -2015

[68 rows x 12 columns]

In [38]:
import pandas as pd
df23=pd.read_csv(r'F:\dm\1 - Copy\Meghalaya.csv')
print (df23)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016         0.003               0.124                 0.003
64      NaN    TOTAL         0.268               6.647                 0.253
65      NaN  Average         0.009               0.196                 0.009
66      NaN  Maximum         0.095                4.77                 0.095
67      NaN   (Year)          1987                1983                  1987

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                  17.73                     1412                  15.477
64                843.108                    43969                  91.165
65                 25.549                     1418                   3.039
66                    707                    21068                  71.203
67                   2014                     2012                    2014

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                   0                        4                     29.322
64               34140                      173                      967.8
65                1138                        6                     31.219
66                8954                       66                    774.171
67                2012                     2014                       2014

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                      Nil
4                                      Nil
..                                     ...
63                                  62.529
64                                1902.073
65                                  54.345
66                                1552.374
67                                    2014

[68 rows x 12 columns]

In [39]:
import pandas as pd
df24=pd.read_csv(r'F:\dm\1 - Copy\Mizoram.csv')
print (df24)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL         0.732               0.086                 0.233
65      NaN  Average         0.043               0.005                 0.014
66      NaN  Maximum         0.541               0.053                 0.189
67      NaN   (Year)          1993                1976                  2015

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                    NaN                      NaN                     NaN
64                 24.553                    62709                   6.371
65                  1.228                     3300                   0.335
66                  18.49                    57147                   5.311
67                   1997                     2005                    1993

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 NaN                      NaN                       1.79
64                3451                      198                       6.53
65                 216                       12                      0.384
66                3451                      172                       4.69
67                2005                     2005                       1993

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                      Nil
4                                      Nil
..                                     ...
63                                    1.79
64                                  37.454
65                                   1.784
66                                    19.3
67                                    1997

[68 rows x 12 columns]

In [40]:
import pandas as pd
df25=pd.read_csv(r'F:\dm\1 - Copy\Nagaland.csv')
print (df25)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL         0.021               0.376                 0.017
65      NaN  Average         0.001                0.02                 0.001
66      NaN  Maximum         0.009               0.176                 0.009
67      NaN   (Year)         -1993               -2005                 -1993

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                    NaN                      NaN                     NaN
64                 12.516                    50900                  58.818
65                  0.659                     2994                   3.268
66                   8.16                    47045                   29.89
67                  -1993                    -2005                   -2013

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 NaN                      NaN                        NaN
64                9577                      133                     20.644
65                 599                        8                      1.147
66                2860                      133                      11.39
67               -2014                    -2005                      -1993

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                      Nil
4                                      Nil
..                                     ...
63                                       0
64                                  91.978
65                                   4.181
66                                   33.41
67                                   -2013

[68 rows x 12 columns]

In [41]:
import pandas as pd
df26=pd.read_csv(r'F:\dm\1 - Copy\Odisha.csv')
print (df26)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955          0.66                   2                  0.41
3       4.0     1956          0.33                 0.9                  0.09
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016         0.009               0.015                   NaN
64      NaN    TOTAL        29.192             158.974                20.474
65      NaN  Average         0.531                2.89                 0.379
66      NaN  Maximum          3.97                 9.8                  3.97
67      NaN   (Year)          2014               -1990                  2014

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                    7.88                   129591                    1.76
3                    2.15                     3187                    0.09
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                    NaN                        9                    0.05
64               1486.087                  4443602                 877.836
65                 29.722                    80793                  17.915
66                 641.25                   800000                  297.78
67                  -2008                    -1982                   -2008

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                 4641                       79                       0.75
3                 1192                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 NaN                        3                     31.245
64              273083                     2385                  13937.704
65                5355                       47                    278.754
66               51840                      140                    2874.41
67               -2008                    -1972                      -2011

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                    10.39
3                                     2.24
4                                      Nil
..                                     ...
63                                  31.295
64                               16301.627
65                                 271.694
66                                 3158.41
67                                   -2008

[68 rows x 12 columns]

In [42]:
import pandas as pd
df27=pd.read_csv(r'F:\dm\1 - Copy\Puducherry.csv')
print (df27)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953             0                   0                     0
1       2.0     1954             0                   0                     0
2       3.0     1955             0                   0                     0
3       4.0     1956             0                   0                     0
4       5.0     1957             0                   0                     0
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL         0.119               0.602                 0.153
65      NaN  Average         0.002               0.012                 0.003
66      NaN  Maximum          0.05                0.42                 0.022
67      NaN   (Year)         -1977               -1977                 -2008

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                       0                        0                       0
1                       0                        0                       0
2                       0                        0                       0
3                       0                        0                       0
4                       0                        0                       0
..                    ...                      ...                     ...
63                    NaN                      NaN                     NaN
64                 36.415                   136928                   6.858
65                  0.674                     2445                   0.137
66                  17.65                    39660                    4.64
67                  -1993                    -1985                   -1993

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                    0                        0                          0
1                    0                        0                          0
2                    0                        0                          0
3                    0                        0                          0
4                    0                        0                          0
..                 ...                      ...                        ...
63                 NaN                      NaN                        NaN
64                 756                       35                    388.109
65                  15                        1                       7.61
66                 473                        9                      325.8
67                1993                     1994                      -2015

    Damage to crops,houses,public utilities
0                                     0.000
1                                     0.000
2                                     0.000
3                                     0.000
4                                     0.000
..                                      ...
63                                    0.000
64                                  431.382
65                                    6.740
66                                  333.000
67                                -2015.000

[68 rows x 12 columns]

In [43]:
import pandas as pd
df28=pd.read_csv(r'F:\dm\1 - Copy\Punjab.csv')
print (df28)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Neg                 Neg                   Neg
1       2.0     1954          0.01                   0                  0.01
2       3.0     1955          0.92                 Nil                  0.92
3       4.0     1956          0.06                 Nil                  0.06
4       5.0     1957          0.08                 Nil                  0.08
..      ...      ...           ...                 ...                   ...
63     64.0     2016         0.001                   0                 0.001
64      NaN    TOTAL        17.819              29.846                14.314
65      NaN  Average         0.343               0.649                  0.27
66      NaN  Maximum          2.79                 4.3                  2.79
67      NaN   (Year)         -1988               -1988                 -1988

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                    0.02                      181                    0.01
1                    0.17                      983                    0.04
2                   15.98                   627100                   15.08
3                     0.8                     8014                    0.18
4                    1.61                     5100                    0.03
..                    ...                      ...                     ...
63                   1.14                       20                   0.025
64               1777.617                  2905604                 658.979
65                 31.186                    50097                  11.561
66                  519.9                   627100                  293.43
67                  -1988                    -1955                   -1988

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                    6                        3                        Nil
1                   48                      Nil                        Nil
2                56100                      477                        Nil
3                  567                        8                        Nil
4                  108                      288                        Nil
..                 ...                      ...                        ...
63                   0                       13                      0.495
64              176905                     3129                   1762.376
65                3159                       56                     41.961
66               66335                      699                        477
67               -1988                    -1988                      -1993

   Damage to crops,houses,public utilities
0                                     0.03
1                                     0.21
2                                    31.06
3                                     0.98
4                                     1.64
..                                     ...
63                                    1.66
64                                4198.972
65                                  71.169
66                                 1270.95
67                                   -1988

[68 rows x 12 columns]

In [44]:
import pandas as pd
df29=pd.read_csv(r'F:\dm\1 - Copy\Rajasthan.csv')
print (df29)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016         0.884               4.381                 0.796
64      NaN    TOTAL        18.558              46.255                11.174
65      NaN  Average         0.344               0.984                 0.233
66      NaN  Maximum          3.26                7.99                  3.09
67      NaN   (Year)          1977                1977                  1977

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                     5400                    0.15
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63               1014.221                    14494                  20.378
64               3357.436                  1768400                1101.398
65                 67.149                    32748                  21.181
66               1122.246                   269332                 428.221
67                   2015                     2006                    2003

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                 1405                       15                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 635                      129                    164.514
64              671564                     2908                   3504.998
65               13705                       56                       70.1
66              230220                      478                    2100.51
67                2006                     1979                       1998

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                     0.15
4                                      Nil
..                                     ...
63                                1199.113
64                                7963.832
65                                 144.797
66                                 2314.69
67                                    1998

[68 rows x 12 columns]

In [45]:
import pandas as pd
df30=pd.read_csv(r'F:\dm\1 - Copy\Sikkim.csv')
print (df30)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Nil                 Nil                   Nil
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL         1.821               0.935                 1.241
65      NaN  Average         0.076               0.033                 0.054
66      NaN  Maximum          1.17                0.31                   0.6
67      NaN   (Year)          2000                2012                  2000

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                     Nil                      Nil                     Nil
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                    NaN                        6                     NaN
64                 22.898                    20350                   9.283
65                  0.848                      754                   0.404
66                  7.634                     9746                    5.56
67                   1984                     1986                    2012

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                  Nil                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 NaN                      NaN                        NaN
64                5165                      277                    701.267
65                 207                       11                     21.915
66                3260                      107                     580.71
67                1983                     1983                       2012

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                      Nil
4                                      Nil
..                                     ...
63                                       0
64                                 733.448
65                                  21.572
66                                  586.27
67                                    2012

[68 rows x 12 columns]

In [46]:
import pandas as pd
df31=pd.read_csv(r'F:\dm\1 - Copy\Tamil Nadu.csv')
print (df31)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954           Nil                 Nil                   Nil
2       3.0     1955           Nil                 Nil                   Nil
3       4.0     1956           Neg                 Nil                   Neg
4       5.0     1957          0.03                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL          5.51              55.836                 2.324
65      NaN  Average         0.167               1.801                 0.073
66      NaN  Maximum         1.466               29.93                 0.383
67      NaN   (Year)          2010                1973                  2015

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                     Nil                      Nil                     Nil
2                     Nil                      Nil                     Nil
3                    0.01                      281                     Neg
4                     Nil                     2791                     Neg
..                    ...                      ...                     ...
63                    NaN                      NaN                     NaN
64               3119.948                  5499201                 144.877
65                 97.498                   124982                   4.261
66               2782.788                  3015270                   33.88
67                   2015                     2015                    1977

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                        Nil
2                  Nil                      Nil                        Nil
3                    3                       15                        Nil
4                  222                        4                        Nil
..                 ...                      ...                        ...
63                 NaN                      NaN                        NaN
64               93226                     3704                  24060.691
65                2274                       82                    687.448
66               22652                      586                  23129.722
67                1977                     1977                       2015

   Damage to crops,houses,public utilities
0                                      Nil
1                                      Nil
2                                      Nil
3                                     0.01
4                                      Neg
..                                     ...
63                                       0
64                               27325.516
65                                 650.608
66                                25912.51
67                                    2015

[68 rows x 12 columns]

In [47]:
import pandas as pd
df32=pd.read_csv(r'F:\dm\1 - Copy\Tripura.csv')
print (df32)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Nil
1       2.0     1954          0.01                0.05                   Neg
2       3.0     1955          0.01                 0.1                   Neg
3       4.0     1956          0.03                0.11                   Neg
4       5.0     1957           Nil                 Nil                   Nil
..      ...      ...           ...                 ...                   ...
63     64.0     2016         0.037               0.091                 0.019
64      NaN    TOTAL         1.472               6.404                  0.47
65      NaN  Average         0.031               0.133                 0.011
66      NaN  Maximum          0.33                 0.7                 0.053
67      NaN   (Year)          1963                1984                  1993

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                     Nil                      Nil                     Nil
1                   0.028                      Nil                     Nil
2                   0.057                      Nil                     Nil
3                    0.13                     1428                   0.025
4                     Nil                      Nil                     Nil
..                    ...                      ...                     ...
63                 89.122                      455                   0.235
64                497.229                   291133                  69.157
65                   9.75                     6194                   1.608
66                247.908                    45988                  20.735
67                   2015                     1993                    2015

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                  Nil                      Nil                        Nil
1                  Nil                      Nil                      0.011
2                  Nil                      Nil                      0.011
3                   96                      Nil                        Nil
4                  Nil                      Nil                        Nil
..                 ...                      ...                        ...
63                 NaN                        3                        NaN
64               30759                      313                    163.981
65                 684                        7                      3.565
66                7761                       54                      42.12
67                1993                     1984                       2015

   Damage to crops,houses,public utilities
0                                      Nil
1                                    0.039
2                                    0.068
3                                    0.155
4                                      Nil
..                                     ...
63                                  89.357
64                                 730.368
65                                  14.046
66                                 310.763
67                                    2015

[68 rows x 12 columns]

In [48]:
import pandas as pd
df33=pd.read_csv(r'F:\dm\1 - Copy\Uttar Pradesh.csv')
print (df33)

    Sl. No.     Year  Area affected  Population affected  \
0       1.0     1953          0.910               14.370
1       2.0     1954          1.350                3.400
2       3.0     1955          4.130               14.000
3       4.0     1956          2.500                8.600
4       5.0     1957          1.700                4.190
..      ...      ...            ...                  ...
63     64.0     2016          0.569                2.032
64      NaN    Total        103.942              413.985
65      NaN  Average          1.650                6.469
66      NaN  Maximum          7.340               30.350
67      NaN   (Year)       1978.000             1980.000

    Damage to Crops(area)  Damage to Crops(value)  Damage to Houses(number)  \
0                   0.000                  10.820                     80443
1                   0.740                   6.820                     19550
2                   2.570                  26.380                    768264
3                   0.000                  21.480                    401889
4                   0.000                  10.670                    263151
..                    ...                     ...                       ...
63                  0.277                 123.776                     35525
64                 61.962                8476.266                  14378491
65                  0.984                 134.544                    224664
66                  5.200                 967.530                   1923134
67               1979.000                1985.000                      1980

    Damage to Houses(value)  Cattle lost(number)  Human lives lost(number)  \
0                     1.110                341.0                      23.0
1                     0.190               1555.0                      27.0
2                     2.820               5694.0                     231.0
3                     6.600               2595.0                     155.0
4                     4.620               1281.0                     193.0
..                      ...                  ...                       ...
63                      NaN                293.0                      74.0
64                 2177.533              90268.0                   18440.0
65                   35.121               1433.0                     293.0
66                  254.550               7430.0                    1390.0
67                 1982.000               1978.0                    1998.0

   Damage to public utilities  Damage to crops,houses,public utilities
0                           1                                   12.930
1                         1.5                                    8.510
2                         0.6                                   29.800
3                         0.5                                   28.580
4                           0                                   15.290
..                        ...                                      ...
63                        NaN                                  123.776
64                   8766.785                                19420.584
65                    143.718                                  303.447
66                    3252.83                                 3315.425
67                       2001                                 2001.000

[68 rows x 12 columns]

In [49]:
import pandas as pd
df34=pd.read_csv(r'F:\dm\1 - Copy\Uttarakhand.csv')
print (df34)

    Sl. No.     Year  Area affected Population affected  \
0       1.0     1953          0.910               14.37
1       2.0     1954          1.350                 3.4
2       3.0     1955          4.130                  14
3       4.0     1956          2.500                 8.6
4       5.0     1957          1.700                4.19
..      ...      ...            ...                 ...
63     64.0     2016          0.010                 NaN
64      NaN    TOTAL          0.072               0.156
65      NaN  Average          0.005               0.012
66      NaN  Maximum          0.059               0.109
67      NaN   (Year)      -2013.000               -2013

    Damage to Crops(area)  Damage to Crops(value)  Damage to Houses(number)  \
0                   0.000                  10.820                     80443
1                   0.740                   6.820                     19550
2                   2.570                  26.380                    768264
3                   0.000                  21.480                    401889
4                   0.000                  10.670                    263151
..                    ...                     ...                       ...
63                  0.010                   4.200                      3324
64                  0.071                3063.200                     33222
65                  0.005                 204.213                      2076
66                  0.059                3059.000                     20141
67              -2013.000               -2013.000                     -2013

    Damage to Houses(value)  Cattle lost(number)  Human lives lost(number)  \
0                     1.110                  341                        23
1                     0.190                 1555                        27
2                     2.820                 5694                       231
3                     6.600                 2595                       155
4                     4.620                 1281                       193
..                      ...                  ...                       ...
63                    9.397                  823                       114
64                 1514.397                21386                      1363
65                  100.960                 1337                        85
66                 1505.000                16215                       580
67                -2013.000                -2013                     -2013

   Damage to public utilities  Damage to crops,houses,public utilities
0                           1                                   12.930
1                         1.5                                    8.510
2                         0.6                                   29.800
3                         0.5                                   28.580
4                           0                                   15.290
..                        ...                                      ...
63                     774.64                                  788.237
64                   35751.64                                40329.237
65                   2383.443                                 2520.577
66                      34977                                39541.000
67                      -2013                                -2013.000

[68 rows x 12 columns]

In [50]:
import pandas as pd
df35=pd.read_csv(r'F:\dm\1 - Copy\West Bengal.csv')
print (df35)

    Sl. No.     Year Area affected Population affected Damage to Crops(area)  \
0       1.0     1953           Nil                 Nil                   Neg
1       2.0     1954          0.42                 Nil                   Neg
2       3.0     1955          0.35                 Nil                   Neg
3       4.0     1956          2.65                 0.9                   0.4
4       5.0     1957          1.16                 0.1                   Neg
..      ...      ...           ...                 ...                   ...
63     64.0     2016           NaN                 NaN                   NaN
64      NaN    TOTAL        49.537             244.227                18.491
65      NaN  Average         0.799                4.07                 0.313
66      NaN  Maximum          3.08                21.8                  2.49
67      NaN   (Year)         -1978               -2000                 -2007

   Damage to Crops(value) Damage to Houses(number) Damage to Houses(value)  \
0                    0.05                      Neg                    0.01
1                     7.6                      Neg                       1
2                     0.5                      600                     Neg
3                    7.42                   199556                     Neg
4                   0.007                      225                     Neg
..                    ...                      ...                     ...
63                    NaN                      NaN                     NaN
64              20957.852                 18222914               12485.075
65                343.571                   303715                 219.036
66               11433.68                  2194858                 7895.63
67                  -2015                    -2000                   -2015

   Cattle lost(number) Human lives lost(number) Damage to public utilities  \
0                 1000                      Nil                        0.1
1                 1500                      142                          2
2                   20                        2                          1
3                 2004                       55                       0.33
4                    0                        2                        Nil
..                 ...                      ...                        ...
63                 NaN                      NaN                        NaN
64              750710                    10489                  10511.865
65               12307                      187                    184.419
66              221826                     2730                    6023.96
67               -1978                    -1968                      -2015

   Damage to crops,houses,public utilities
0                                     0.16
1                                     10.6
2                                      1.5
3                                     7.75
4                                    0.007
..                                     ...
63                                       0
64                               43954.792
65                                 708.948
66                                25353.27
67                                   -2015

[68 rows x 12 columns]